# Generated by Django 5.1 on 2024-08-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Administrateur'), ('Candidat', 'Candidat'), ('Enseignant', 'Enseignant'), ('Etudiant', 'Étudiant')], default='Candidat', max_length=30, null=True),
        ),
    ]
