# Generated by Django 5.1 on 2024-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='mot_de_passe',
            field=models.CharField(max_length=30),
        ),
    ]
