# Generated by Django 5.1 on 2024-08-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_candidat_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], default='Homme', max_length=30),
        ),
    ]
