# Generated by Django 5.1 on 2024-08-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='images/'),
        ),
    ]
