# Generated by Django 5.1 on 2024-08-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_utilisateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='images/'),
        ),
    ]
