# Generated by Django 5.1 on 2024-08-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_domaine_image_alter_programme_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='code_programme',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='code_programme',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='code_session',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
