# Generated by Django 5.1 on 2024-08-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.domaine'),
        ),
    ]
