# Generated by Django 5.1 on 2024-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_utilisateur_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
