# Generated by Django 5.1 on 2024-08-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_utilisateur_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='programme',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='programme',
            field=models.ManyToManyField(blank=True, to='auth_app.programme'),
        ),
    ]
