# Generated by Django 5.1 on 2024-09-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_remove_utilisateur_programme_utilisateur_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='domaine',
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=30)),
                ('nbcredits', models.EmailField(max_length=254)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.domaine')),
                ('programme', models.ManyToManyField(blank=True, to='auth_app.programme')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.session')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='domaine',
            field=models.ManyToManyField(blank=True, to='auth_app.domaine'),
        ),
    ]
