# Generated by Django 5.1 on 2024-09-16 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_delete_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='diplome',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='passport',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('Diplome', 'Diplôme'), ('ActeNaissance', 'Acte de naissance'), ('Passeport', 'Passeport'), ('LettreMotivation', 'Lettre de motivation'), ('Autre', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
