# Generated by Django 5.1 on 2024-09-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_utilisateur_diplome_utilisateur_passport_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
