# Generated by Django 5.1 on 2024-09-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_utilisateur_diplome_alter_utilisateur_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='frais_paye',
            field=models.BooleanField(default=False),
        ),
    ]
