# Generated by Django 5.1 on 2024-09-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('batiment', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cours',
            name='horaire',
        ),
        migrations.AlterField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='cours_app.salle'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='cours_app.salle'),
        ),
    ]
