# Generated by Django 5.1 on 2024-09-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0002_salle_remove_cours_horaire_alter_cours_salle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='salle',
        ),
    ]
