# Generated by Django 5.1 on 2024-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_frais_admission_utilisateur_frais_paye'),
        ('cours_app', '0003_remove_cours_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='session',
        ),
        migrations.AddField(
            model_name='cours',
            name='programme',
            field=models.ManyToManyField(related_name='cours', to='auth_app.programme'),
        ),
        migrations.AddField(
            model_name='cours',
            name='session',
            field=models.ManyToManyField(related_name='cours', to='auth_app.session'),
        ),
    ]
