# Generated by Django 5.1 on 2024-09-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0004_remove_cours_programme_remove_cours_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='professeur',
        ),
        migrations.AddField(
            model_name='horaire',
            name='professeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Enseignant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to=settings.AUTH_USER_MODEL),
        ),
    ]
