# Generated by Django 5.1 on 2024-09-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0006_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents_cours/')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cours_app.cours')),
            ],
        ),
    ]
