# Generated by Django 5.1 on 2024-09-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0007_coursdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('consignes', models.TextField()),
                ('date_limite', models.DateTimeField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devoirs/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='cours_app.evaluation')),
            ],
        ),
    ]
