# Generated by Django 5.1 on 2024-09-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0009_remove_devoir_evaluation_devoir_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nogroupe', models.CharField(max_length=20, unique=True)),
                ('nom_groupe', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attribution',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='cours_app.groupe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours_app.groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together={('cours', 'professeur', 'groupe')},
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'cours', 'groupe')},
        ),
    ]
