# Generated by Django 5.1 on 2024-09-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0012_soumissionevaluation_soumission_effectuee'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='est_attribuee',
            field=models.BooleanField(default=False),
        ),
    ]
