# Generated by Django 5.1 on 2024-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0013_note_est_attribuee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horaire',
        ),
    ]
