# Generated by Django 5.1 on 2024-09-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours_app', '0014_delete_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='cours_app.groupe')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='cours_app.salle')),
            ],
            options={
                'unique_together': {('groupe', 'salle', 'jour', 'heure_debut')},
            },
        ),
    ]
